CREATE TABLE person(
    id int GENERATED by DEFAULT AS IDENTITY PRIMARY KEY ,
    username varchar(100) NOT NULL ,
    year_of_birth INT NOT NULL ,
    password varchar NOT NULL
);

INSERT INTO person(username, year_of_birth, password) VALUES ('user1', 1970, 'password1');
INSERT INTO person(username, year_of_birth, password) VALUES ('user2', 1970, 'password1');